# see http://doc.gitlab.com/ci/yaml/README.html

before_script:
  - bundle install

ruby_codestyle:
  script: bundle exec rubocop -R

tests:
  script:
    - bundle exec rake db:migrate:reset RAILS_ENV=test
    - bundle exec rake db:seed RAILS_ENV=test
    - bundle exec rspec

security:
  script: bundle exec brakeman -z
